### ISSUE TITLE
Change image of pressed bubble item index?

### ISSUE THREAD

**Issue by hyd00** [limitlessvirtual/LIVBubbleMenu-iOS#9]
How to change the image of the pressed item?

**Comment by lvandyk** [comment]
Are you referring to the on touch down of a bubble? There is no way to do that. What you could do is fork the repo and send through a pull request.

What you would need to do is allow the menu to be initialized with another array of UIImages for the pressed state. Then add an additional target in the createButtonWithImage function to another function that changes the image!

**Comment by hyd00** [comment]
Yeah I thought so.. Just wanted to confirm if this is in the library already or not.. sigh. Thanks @lvandyk
